name: LightExchanger
version: '${project.version}'
main: net.parcival.lightexchanger.LightExchanger
api-version: 1.19
authors: [ Parcival ]
description: Exchange torches for light block
commands:
  exchangelight:
